#!/bin/sh

# set-pi-time - get the current time on this host and set the Pi time from it


PIHOST=vmts@veropi.local


# turn off NTP on the Pi and wait 3 seconds for it to take effect

echo Disabling NTP on Pi
ssh -t $PIHOST sudo timedatectl set-ntp false
sleep 3


# get the current time and set the time on the Pi using it, all in UTC
#
# unfortunately, the delay in authenticating to the Pi means the clock will
# be out by a few seconds but this is not a major issue, in our case, and
# working around it would be complicated

echo Setting clock manually on Pi
TIME="$(date -u '+%Y-%m-%d %H:%M:%S')"
ssh -t $PIHOST sudo timedatectl set-time \"$TIME UTC\"


# wait 5 seconds just so you can confirm the time

echo Done
sleep 5
